--------------------------------------------------------
--  File created - Sunday-March-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PATIENTDETAILS
--------------------------------------------------------

  CREATE TABLE "ANKIT"."PATIENTDETAILS" 
   (	"PATIENTID" NUMBER(19,0), 
	"PATIENTNAME" VARCHAR2(50), 
	"PATIENTAGE" NUMBER(2,0), 
	"FATHERNAME" VARCHAR2(50), 
	"GENDER" VARCHAR2(5), 
	"FILETYPE" VARCHAR2(10), 
	"FILEPATH" VARCHAR2(50), 
	"ENTRYDATE" DATE, 
	"FILENAME" VARCHAR2(50), 
	"RELATIONTYPE" VARCHAR2(20)
   )
REM INSERTING into ANKIT.PATIENTDETAILS
SET DEFINE OFF;
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (8,'wedw',0,'erer','M','ULTRASOUND','C:\DOCS\ULTRASOUND\wedw__1583767600003.doc',to_date('09-MAR-20','DD-MON-RR'),'civil hospital.doc','S/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (10,'demo',0,'dd','M','CTSCAN','C:\DOCS\CTSCAN\demo__1583767880082.doc',to_date('09-MAR-20','DD-MON-RR'),'CIRRHOSIS LIVER WITH ASCITES.doc','S/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (11,'ramesh',0,'suresh','M','CTSCAN','C:\DOCS\CTSCAN\ramesh__1583768314645.doc',to_date('09-MAR-20','DD-MON-RR'),'CC.doc','S/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (12,'next',0,'next','M','ULTRASOUND','C:\DOCS\ULTRASOUND\next__1583768768515.doc',to_date('09-MAR-20','DD-MON-RR'),'CC.doc','D/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (13,'line',0,'space','F','ULTRASOUND','C:\DOCS\ULTRASOUND\line__1583769218162.doc',to_date('09-MAR-20','DD-MON-RR'),'CC.doc','W/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (14,'229',0,'322','M','ULTRASOUND','C:\DOCS\ULTRASOUND\229__1583810756659.doc',to_date('10-MAR-20','DD-MON-RR'),'CIRRHOSIS LIVER WITH ASCITES.doc','W/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (15,'229',0,'322','M','ULTRASOUND','C:\DOCS\ULTRASOUND\229__1583810777220.docx',to_date('10-MAR-20','DD-MON-RR'),'DMRP-User Manual For Distributor.docx','W/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (16,'demo',0,'demo','M','ULTRASOUND','C:\DOCS\ULTRASOUND\demo__1583810872010.doc',to_date('10-MAR-20','DD-MON-RR'),'CIRRHOSIS LIVER WITH ASCITES.doc','W/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (17,'demo',0,'demo','F','ULTRASOUND','C:\DOCS\ULTRASOUND\demo__1583811053377.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','S/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (18,'demo',0,'demo','F','ULTRASOUND','C:\DOCS\ULTRASOUND\demo__1583811128576.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','S/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (19,'demo',0,'eke','M','ULTRASOUND','C:\DOCS\ULTRASOUND\demo__1583811211849.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','S/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (20,'line',0,'line','M','CTSCAN','C:\DOCS\CTSCAN\line__1583811682956.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','S/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (21,'demo',0,'demo','M','ULTRASOUND','C:\DOCS\ULTRASOUND\demo__1583811897585.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','D/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (22,'wwe',0,'wwr','M','ULTRASOUND','C:\DOCS\ULTRASOUND\wwe__1583812458602.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','S/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (23,'demo',0,'de,o','M','ULTRASOUND','C:\DOCS\ULTRASOUND\demo__1583812977297.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','W/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (24,'demo',0,'dmoe','M','ULTRASOUND','C:\DOCS\ULTRASOUND\demo__1583813067493.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','S/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (25,'finaal',0,'final','M','POLICECASE','C:\DOCS\POLICECASE\finaal__1583813138488.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','D/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (26,'demo',0,'dmeo','M','CTSCAN','C:\DOCS\CTSCAN\demo__1583813197228.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','S/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (27,'ultra',0,'sound','M','ULTRASOUND','C:\DOCS\ULTRASOUND\ultra__1583813266269.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','S/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (28,'ultra',0,'sound','M','ULTRASOUND','C:\DOCS\ULTRASOUND\ultra__1583813273572.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','W/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (29,'ultra',0,'sound','M','ULTRASOUND','C:\DOCS\ULTRASOUND\ultra__1583813280087.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','D/O');
Insert into ANKIT.PATIENTDETAILS (PATIENTID,PATIENTNAME,PATIENTAGE,FATHERNAME,GENDER,FILETYPE,FILEPATH,ENTRYDATE,FILENAME,RELATIONTYPE) values (30,'demo',0,'dmeo','M','ULTRASOUND','C:\DOCS\ULTRASOUND\demo__1583814921660.doc',to_date('10-MAR-20','DD-MON-RR'),'CC.doc','W/O');


